### ISSUE TITLE
0.3.0.dev的代码没有开源吗？

### ISSUE THREAD

**Issue by killomsc** [secretflow/kuscia-envoy#8]
我在kuscia的dockerfile看到，envoy的版本是
ARG KUSCIA_ENVOY_IMAGE="secretflow/kuscia-envoy:0.3.0.dev231122"
请问下，0.3.0.dev的代码没有开源吗？

**Comment by UniqueMarvin** [comment]
感谢提醒，我们03-15 会统一同步一下代码

**Comment by UniqueMarvin** [comment]
hi @killomsc  envoy 代码已更新
